version: '2.1'
services:
  radio-player:
    build: ./radio-player
    privileged: true
    expose:
      - "6020"
    environment:
      - RADIO_ENABLED=1
  controller:
    build: ./controller
    privileged: true
    expose:
      - "8001"  # tuning-knob
      - "8002"  # volume-knob
    environment:
      - RADIO_HOSTNAME=radio-player
      - RADIO_PORT=6020
      - GREEN_GPIO_PIN=6
      - YELLOW_GPIO_PIN=26
      - INITIAL_FREQUENCY_MHZ=101.9
      # I2C|NONE
      - DISPLAY_TYPE=I2C
  tuning-knob:
    image: bhcr.io/ramiro_gonzalez/rotary-knob
    privileged: true
    environment: 
      - RENC_LISTENER_ADDRESS=controller
      - RENC_LISTENER_PORT=8001
      - RENC_CLK_GPIO_PIN=17
      - RENC_DT_GPIO_PIN=27
      - RENC_SW_GPIO_PIN=22
      - LOG_ENABLED=1
  tuning-keyreader:
    build: ./keyreader-usb      
    privileged: true
    stdin_open: true # docker run -i
    tty: true
    environment: 
      - LISTENER_ADDRESS=controller  # see the app container
      - LISTENER_PORT=8001  # see the app container
      - LEFT_KEY=a
      - RIGHT_KEY=d
      - PUSH_KEY=z
      - LOG_ENABLED=0
      - VENDOR_ID=05ac
      - PRODUCT_ID=020b
      # Bus 001 Device 006: ID 05ac:020b Apple, Inc. Pro Keyboard [Mitsumi, A1048/US layout]
  volume-knob:
    image: bhcr.io/ramiro_gonzalez/rotary-knob 
    privileged: true
    environment: 
      - RENC_LISTENER_ADDRESS=controller  # see the app container
      - RENC_LISTENER_PORT=8002  # see the app container
      - RENC_CLK_GPIO_PIN=25
      - RENC_DT_GPIO_PIN=5
      - RENC_SW_GPIO_PIN=16
      - LOG_ENABLED=1
  volume-keyreader:
    build: ./keyreader-usb      
    privileged: true
    environment: 
      - LISTENER_ADDRESS=controller  # see the app container
      - LISTENER_PORT=8002  # see the app container
      - LEFT_KEY=s
      - RIGHT_KEY=w
      - PUSH_KEY=x
      - LOG_ENABLED=0
      - VENDOR_ID=05ac
      - PRODUCT_ID=020b


  # fbcp:
  #   image: balenablocks/fbcp
  #   privileged: true
  #   environment:
  #     - FBCP_DISPLAY=waveshare-st7789vw-hat
  #     - BALENA_HOST_CONFIG_hdmi_force_hotplug=1
