version: '2'
services:
  # radio-player:
  #   build: ./radio-player
  #   privileged: true
  #   expose:
  #     - "6020"
  controller:
    build: ./controller
    privileged: true
    expose:
      - "8001"
    environment:
      - RADIO_HOSTNAME=radio-player
      - RADIO_PORT=6020
      - GREEN_GPIO_PIN=6
      - YELLOW_GPIO_PIN=26
    labels:
      io.balena.features.kernel-modules: '1'      
  # dial:
  #   build: ./rotary-reader
  #   privileged: true
  #   ports:
  #     - "80:80"
  #   environment: 
  #     - LISTENER_ADDRESS=controller
  #     - LISTENER_PORT=8001
  #     - CLK_GPIO_PIN=17
  #     - DT_GPIO_PIN=27
  #     - SW_GPIO_PIN=22
  fbcp:
    image: balenablocks/fbcp
    privileged: true
    environment:
      - FBCP_DISPLAY=waveshare-st7789vw-hat
      - BALENA_HOST_CONFIG_hdmi_force_hotplug=1